// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwoFAAPI.Data;

#nullable disable

namespace TwoFAAPI.Migrations
{
    [DbContext(typeof(FADBContext))]
    [Migration("20231011113129_emailandpassfieldadd")]
    partial class emailandpassfieldadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwoFAAPI.Data.HrEmp", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpId"));

                    b.Property<string>("BackupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Is2faenable")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TotpDisableon")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TotpDisablereason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TotpEnableon")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TotpSecretkey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotpVerifyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpId");

                    b.ToTable("HrEmp");
                });

            modelBuilder.Entity("TwoFAAPI.Data.HrEmpTwoFABackupcode", b =>
                {
                    b.Property<int>("BackupCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BackupCodeId"));

                    b.Property<string>("BackupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrgId")
                        .HasColumnType("integer");

                    b.HasKey("BackupCodeId");

                    b.ToTable("HrEmpTwoFABackupcode");
                });
#pragma warning restore 612, 618
        }
    }
}
